line-length = 88

# ignore specific error from lint with ruff
[lint]
ignore = ["F541", "F841", "E711", "E721", "F541", "E741", "F401", "F403", "E712", "E731", "F811"]


[format]
# according PEP8 python, double quotes for strings.
quote-style = "double"
