# This module is part of CAiMIRA. Please see the repository at
# https://gitlab.cern.ch/caimira/caimira for details of the license and terms of use.
name: CI

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  test-caimira-py311:
    name: Test CAiMIRA with Python 3.11
    runs-on: ubuntu-latest
    env:
      PROJECT_ROOT: "caimira"
      PY_VERSION: "3.11"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PY_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          cd ${{ env.PROJECT_ROOT }}
          pip install --upgrade pip
          pip install -e .[test]

      - name: Run Tests
        run: |
          cd caimira
          python -m pytest

  test-cern-caimira-py311:
    name: Test CERN CAiMIRA with Python 3.11
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/live/caimira-test' && !startsWith(github.ref, 'refs/tags/')
    env:
      PROJECT_ROOT: "cern_caimira"
      PY_VERSION: "3.11"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PY_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          cd caimira
          pip install --upgrade pip
          pip install -e .[test]
          cd ../${{ env.PROJECT_ROOT }}
          pip install --upgrade pip
          pip install -e .[test]

      - name: Run Tests
        run: |
          cd cern_caimira
          python -m pytest

  test-caimira-py39:
    name: Test CAiMIRA with Python 3.9
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/live/caimira-test' && !startsWith(github.ref, 'refs/tags/')
    env:
      PROJECT_ROOT: "caimira"
      PY_VERSION: "3.9"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PY_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          cd ${{ env.PROJECT_ROOT }}
          pip install --upgrade pip
          pip install -e .[test]

      - name: Run Tests
        run: |
          cd caimira
          python -m pytest

  test-cern-caimira-py39:
    name: Test CERN CAiMIRA with Python 3.9
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/live/caimira-test' && !startsWith(github.ref, 'refs/tags/')
    env:
      PROJECT_ROOT: "cern_caimira"
      PY_VERSION: "3.9"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PY_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          cd caimira
          pip install --upgrade pip
          pip install -e .[test]
          cd ../${{ env.PROJECT_ROOT }}
          pip install --upgrade pip
          pip install -e .[test]

      - name: Run Tests
        run: |
          cd cern_caimira
          python -m pytest
